#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Secrets belong in .env.local, which is gitignored. Never .env.
ENV_FILE=".env.local"

DASHBOARD="https://pay.getfansee.com"

banner "PayRam Phase 0 configuration"

# ── 1. Project API key ────────────────────────────────────────────────────
stage "PayRam: project API key"
say "This one key does double duty: it authenticates our calls to"
say "/api/v1/payment AND it is the HMAC key PayRam signs webhooks with."
open_url "$DASHBOARD/login"
step "Log in, then find the API key generator in the left menu under Developers."
note "PayRam issues one key per project. If it is not under Developers, check Settings."
step "Generate (or reveal) the key for the GetFanSee project and copy it."
ask_secret PAYRAM_API_KEY "Paste the PayRam project API key:"
write_env PAYRAM_API_KEY "$PAYRAM_API_KEY"
say ""
say "PAYRAM_WEBHOOK_SECRET stays empty: PayRam signs with the API key above."
say "Only fill it if this instance was given a separate signing key."
write_env PAYRAM_WEBHOOK_SECRET ""

# ── 2. Site URL ───────────────────────────────────────────────────────────
stage "PayRam: instance base URL"
say "PayRam serves the dashboard and the API from the same address, so the"
say "Site URL it reports is exactly what PAYRAM_BASE_URL must be."
open_url "$DASHBOARD"
step "Go to Settings → Site URL and read 'Current site URL'."
warn "If it shows http:// while the site is HTTPS, a proxy is terminating SSL."
note "The root user can correct the protocol on that same page. Fix it there, not here."
ask PAYRAM_BASE_URL "Paste the Site URL (include the port if there is one):"
write_env PAYRAM_BASE_URL "$PAYRAM_BASE_URL"

# ── 3. Deposit + cold wallet, locked to one asset ─────────────────────────
stage "PayRam: deposit wallet on Base"
say "We accept USDC on Base only. A second asset or chain means a second set"
say "of confirmation rules, a second reconciliation series and a second key"
say "that must never leak, for no extra revenue."
open_url "$DASHBOARD"
step "Wallet management → Deposit wallet → + Set Up Deposit Wallet."
step "Pick EVM, then choose the GetFanSee project."
step "Name the wallet and connect your MASTER wallet in the browser extension."
step "Enter your COLD wallet address, then Deploy contract and confirm on-chain."
warn "The cold wallet MUST differ from the master wallet, and the master wallet"
warn "needs ETH on Base to pay for the deployment transaction."
note "You hold the cold wallet keys. PayRam never stores them."
say ""
step "Then use 'Create Test Payment Link' for a \$1 payment to prove the flow."
if ! confirm "Deposit wallet deployed on Base and cold wallet address saved?"; then
  SKIPPED+=("Deploy the Base deposit wallet + cold wallet in Wallet management")
fi
if ! confirm "Is the project restricted to USDC on Base only (no other asset enabled)?"; then
  SKIPPED+=("Lock the project to USDC on Base (Phase 0 gate 2.2)")
fi

# ── 4. Webhook endpoint ───────────────────────────────────────────────────
stage "PayRam: webhook endpoint"
say "The webhook is the ONLY path that credits a fan's wallet, so pointing it at"
say "the wrong host means fans pay and nothing happens — silently, forever."
say ""
warn "Two hosts are easy to confuse here, and both are wrong:"
note "  pay.getfansee.com  — PayRam itself. No /api/webhooks/payram route exists."
note "  getfansee.com      — as of 2026-08 the apex DNS still points at a"
note "                       third-party PHP waitlist page, NOT this app."
say ""
say "The Next.js app is the Vercel project 'getfansee-auth', normally reachable"
say "at https://demo.getfansee.com. Verify before you paste:"
note "  curl -s -o /dev/null -w '%{http_code}' https://demo.getfansee.com/home   # expect 200"
ask APP_ORIGIN "App origin that serves this repo (e.g. https://demo.getfansee.com):"
say ""
open_url "$DASHBOARD"
step "Settings → Webhook → Add Endpoint."
step "Endpoint URL: ${APP_ORIGIN%/}/api/webhooks/payram"
step "Add a short description, save, and make sure the endpoint is marked active."
if ! confirm "Webhook endpoint saved and active?"; then
  SKIPPED+=("Register ${APP_ORIGIN%/}/api/webhooks/payram under Settings → Webhook")
fi
say ""
note "Open question for PayRam support: the API has no redirectURL parameter and"
note "the docs describe no return-URL setting, so where a fan lands after paying"
note "is unconfirmed. Ask, and record the answer in the Phase 0 doc."
SKIPPED+=("Confirm with PayRam whether a post-payment return URL is configurable")

# ── 5. Production environment ─────────────────────────────────────────────
stage "Vercel: production environment"
say "The values above only configured this machine. Production reads Vercel."
open_url "https://vercel.com/dashboard"
step "Open the GetFanSee project → Settings → Environment Variables."
step "Add PAYRAM_BASE_URL and PAYRAM_API_KEY with the same values you just entered."
step "Leave PAYRAM_WEBHOOK_SECRET unset, and set PAYRAM_ENABLED=false for now."
note "CI needs none of these: unit tests use a fake key and the rail stays off."
if ! confirm "Production environment variables added?"; then
  SKIPPED+=("Add PAYRAM_BASE_URL / PAYRAM_API_KEY to Vercel (PAYRAM_ENABLED=false)")
fi

# ── 6. Keep the rail off until Phase 0 signs off ──────────────────────────
stage "Master switch stays OFF"
say "Configuration is not permission. The rail opens only after the Phase 0"
say "small-amount live loop has run with real money and reconciled to zero."
write_env PAYRAM_ENABLED "false"
say ""
say "Next, run the checks that do not need real money:"
note "  pnpm test:unit tests/unit/lib/payram.test.ts"
note "  pnpm payram:replay --reference=<reference_id from a real created payment>"
say ""
say "Then work through Gate 3 in:"
note "  docs/planning/payram-phase0-validation.md"
warn "Do not set PAYRAM_ENABLED=true until every Gate 4 box is ticked."
# ──────────────────────────────────────────────────────────────────────────

finish
